### ISSUE TITLE
Add leaf drop or coloration to data

### ISSUE THREAD

**Issue by dbuona** [lizzieinvancouver/wildhellgarden#7]
Please add leaf drop or leaf coloration to data (clean_obsdata_phases.csv). Choose whichever phase has the most observations! Thanks!

**Comment by cchambe12** [comment]
@dbuona okay! I added in leaf color since that had the most data. Most years were missing leaf drop entirely (or more likely were miscoded...). I also noticed a couple of code errors so I cleaned those up but hopefully they won't change the models too much. Please let me know if something looks very wrong!

**Comment by dbuona** [comment]
Thanks!
